version: 2.1
jobs:
  build:
    working_directory: ~/neo-3-preview
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: lint
          # For now we will treat all warnings as errors https://github.com/facebook/create-react-app/issues/3657
          command: npm run ci-lint
      - run: # run tests
          name: test
          command: npm run test

  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: configure git settings for deployment
          command: |
            git config user.email "ci-build@coz.io"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "f2:62:34:3a:55:5a:1c:b8:23:0a:13:23:72:1a:91:11"
      - run:
          name: Deploy docs to gh-pages branch
          command: npm run deploy

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # filters:
          #   branches:
          #     only: master
